//
//  CounterConfigurator.swift
//  DemoWithVIP
//
//  Created by Lương Nhật Lâm on 10/26/17.
//  Copyright (c) 2017 Lương Nhật Lâm. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension CounterViewController: CounterPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension CounterInteractor: CounterViewControllerOutput
{
}

extension CounterPresenter: CounterInteractorOutput
{
}

class CounterConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = CounterConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: CounterViewController)
  {
    let router = CounterRouter()
    router.viewController = viewController
    
    let presenter = CounterPresenter()
    presenter.output = viewController
    
    let interactor = CounterInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
