//
//  CounterModels.swift
//  DemoWithVIP
//
//  Created by Lương Nhật Lâm on 10/26/17.
//  Copyright (c) 2017 Lương Nhật Lâm. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct Counter
{
  struct Something
  {
    struct Request
    {
    }
    struct Increase
    {
    }
    struct Decrease
    {
    }
    struct Response
    {
        var number:Int
    }
    struct ViewModel
    {
        var result:String
    }
  }
}
