//
//  CounterWorker.swift
//  DemoWithVIP
//
//  Created by Lương Nhật Lâm on 10/26/17.
//  Copyright (c) 2017 Lương Nhật Lâm. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class CounterWorker
{
  // MARK: - Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
    
    func increase(number:Int) -> Int {
        var new = number
        new += 1
        return new
    }
    
    func decrease(number:Int) -> Int {
        var new = number
        new -= 1
        return new
    }
}
